// This file is automatically generated by scripts/build-corejs3-shipped-proposals.mjs

export default new Set<string>([
  "esnext.array.group",
  "esnext.array.group-to-map",
  "esnext.iterator.chunks",
  "esnext.iterator.includes",
  "esnext.iterator.join",
  "esnext.iterator.windows",
  "esnext.symbol.metadata",
]);
